// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7UgK5_OoHY0CA3xpJ15u5XzCb9WghMEI',
    appId: '1:767219600485:web:7774ddbeb48843ad848a8c',
    messagingSenderId: '767219600485',
    projectId: 'fir-flutter-codelab-59a35',
    authDomain: 'fir-flutter-codelab-59a35.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-59a35.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOq1sgZIhTEBOgOEKT1_bdTYOcK3PHDg0',
    appId: '1:767219600485:android:9e2e3043b535e54c848a8c',
    messagingSenderId: '767219600485',
    projectId: 'fir-flutter-codelab-59a35',
    storageBucket: 'fir-flutter-codelab-59a35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd63UzKCmqWx3W7-FsIFCaCjwPZVjx4SE',
    appId: '1:767219600485:ios:849d5fb784aa3a6b848a8c',
    messagingSenderId: '767219600485',
    projectId: 'fir-flutter-codelab-59a35',
    storageBucket: 'fir-flutter-codelab-59a35.appspot.com',
    iosClientId: '767219600485-20ee01u3mg8h8bhldjserh72i46vmce0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd63UzKCmqWx3W7-FsIFCaCjwPZVjx4SE',
    appId: '1:767219600485:ios:849d5fb784aa3a6b848a8c',
    messagingSenderId: '767219600485',
    projectId: 'fir-flutter-codelab-59a35',
    storageBucket: 'fir-flutter-codelab-59a35.appspot.com',
    iosClientId: '767219600485-20ee01u3mg8h8bhldjserh72i46vmce0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
